// data.js

export const libraryBooks = [
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", available: true },
  { title: "To Kill a Mockingbird", author: "Harper Lee", available: false },
  { title: "1984", author: "George Orwell", available: true },
  { title: "Pride and Prejudice", author: "Jane Austen", available: true },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    available: false,
  },
  { title: "The Lord of the Rings", author: "J.R.R. Tolkien", available: true },
  { title: "The Diary of a Young Girl", author: "Anne Frank", available: true },
  { title: "Brave New World", author: "Aldous Huxley", available: false },
  { title: "Fahrenheit 451", author: "Ray Bradbury", available: true },
  { title: "Animal Farm", author: "George Orwell", available: true },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    available: true,
  },
  { title: "Wuthering Heights", author: "Emily Brontë", available: false },
  { title: "Jane Eyre", author: "Charlotte Brontë", available: true },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    available: false,
  },
  { title: "The Alchemist", author: "Paulo Coelho", available: true },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    available: true,
  },
  {
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    available: false,
  },
  { title: "The Grapes of Wrath", author: "John Steinbeck", available: true },
  { title: "The Road", author: "Cormac McCarthy", available: true },
  { title: "The Fault in Our Stars", author: "John Green", available: false },
  { title: "Gone Girl", author: "Gillian Flynn", available: true },
  { title: "Little Women", author: "Louisa May Alcott", available: true },
  { title: "The Hunger Games", author: "Suzanne Collins", available: false },
  { title: "Dune", author: "Frank Herbert", available: true },
  { title: "The Martian", author: "Andy Weir", available: true },
  { title: "Ender's Game", author: "Orson Scott Card", available: false },
  { title: "The Book Thief", author: "Markus Zusak", available: true },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", available: true },
  { title: "Catch-22", author: "Joseph Heller", available: false },
  { title: "The Kite Runner", author: "Khaled Hosseini", available: true },
  {
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    available: true,
  },
  {
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    available: false,
  },
  { title: "The Night Circus", author: "Erin Morgenstern", available: true },
  {
    title: "The Time Traveler's Wife",
    author: "Audrey Niffenegger",
    available: false,
  },
  {
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    available: true,
  },
  {
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    available: true,
  },
  { title: "The Chronicles of Narnia", author: "C.S. Lewis", available: true },
  { title: "The Outsiders", author: "S.E. Hinton", available: false },
  {
    title: "The Perks of Being a Wallflower",
    author: "Stephen Chbosky",
    available: true,
  },
  { title: "The Lovely Bones", author: "Alice Sebold", available: true },
  {
    title: "The Curious Incident of the Dog in the Night-Time",
    author: "Mark Haddon",
    available: false,
  },
  { title: "Ready Player One", author: "Ernest Cline", available: true },
  { title: "The Girl on the Train", author: "Paula Hawkins", available: true },
  {
    title: "Station Eleven",
    author: "Emily St. John Mandel",
    available: false,
  },
  { title: "Where the Crawdads Sing", author: "Delia Owens", available: true },
  { title: "Big Little Lies", author: "Liane Moriarty", available: true },
  { title: "Normal People", author: "Sally Rooney", available: false },
  { title: "The Vanishing Half", author: "Brit Bennett", available: true },
  { title: "Anxious People", author: "Fredrik Backman", available: true },
  { title: "Circe", author: "Madeline Miller", available: false },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    available: true,
  },
  { title: "Malibu Rising", author: "Taylor Jenkins Reid", available: true },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    available: false,
  },
  { title: "The Midnight Library", author: "Matt Haig", available: true },
  { title: "The Song of Achilles", author: "Madeline Miller", available: true },
  {
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    available: false,
  },
  { title: "Pachinko", author: "Min Jin Lee", available: true },
  { title: "Educated", author: "Tara Westover", available: true },
  { title: "Becoming", author: "Michelle Obama", available: false },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    available: true,
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    available: true,
  },
  { title: "Born a Crime", author: "Trevor Noah", available: false },
  {
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    available: true,
  },
  { title: "The Power of Habit", author: "Charles Duhigg", available: true },
  { title: "Atomic Habits", author: "James Clear", available: false },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    available: true,
  },
  { title: "Educated", author: "Tara Westover", available: true },
  { title: "You Are a Badass", author: "Jen Sincero", available: false },
];

export const labEquipment = [
  { equipment: "Microscope", status: "Available" },
  { equipment: "Oscilloscope", status: "In Use" },
  { equipment: "3D Printer", status: "Available" },
  { equipment: "Centrifuge", status: "Maintenance" },
  { equipment: "Spectrophotometer", status: "Available" },
  { equipment: "Bunsen Burner", status: "In Use" },
  { equipment: "Fume Hood", status: "Available" },
  { equipment: "pH Meter", status: "In Use" },
  { equipment: "Analytical Balance", status: "Available" },
  { equipment: "Refractometer", status: "Available" },
  { equipment: "Titration Setup", status: "In Use" },
  { equipment: "Thermocycler", status: "Available" },
  { equipment: "Incubator", status: "In Use" },
  { equipment: "Gel Electrophoresis Apparatus", status: "Available" },
  { equipment: "UV-Vis Spectrophotometer", status: "In Use" },
  { equipment: "Cryostat", status: "Available" },
  { equipment: "Water Bath", status: "In Use" },
  { equipment: "Centrifuge Tubes", status: "Available" },
  { equipment: "Petri Dishes", status: "In Use" },
  { equipment: "Hot Plate", status: "Available" },
  { equipment: "Stirring Rod", status: "Available" },
  { equipment: "Micropipette", status: "In Use" },
  { equipment: "Bacteria Incubator", status: "Available" },
  { equipment: "Lab Oven", status: "In Use" },
  { equipment: "Deionized Water System", status: "Available" },
  { equipment: "Chemical Storage Cabinet", status: "Available" },
  { equipment: "Safety Shower", status: "Available" },
  { equipment: "Eyewash Station", status: "In Use" },
  { equipment: "Gas Chromatograph", status: "Available" },
  { equipment: "Liquid Chromatograph", status: "In Use" },
  { equipment: "Fume Extractor", status: "Available" },
  { equipment: "NMR Spectrometer", status: "In Use" },
  { equipment: "Mass Spectrometer", status: "Available" },
  {
    equipment: "Field Emission Scanning Electron Microscope",
    status: "In Use",
  },
  { equipment: "High-Performance Liquid Chromatograph", status: "Available" },
  { equipment: "Thermal Cycler", status: "In Use" },
  { equipment: "X-Ray Diffraction Equipment", status: "Available" },
];
